name: Slither

on: [push, pull_request]

jobs:
  slither:
    name: Run Slither
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Set up CI env
        run: cp .env.ci .env

      - name: Install deps
        run: |
          pip install poetry
          if [ -f pyproject.toml ]; then poetry install; fi

      - name: Run Slither
        run: poetry run slither . --filter-paths contracts/deploy\|node_modules/@openzeppelin/contracts\|eth-sdk/abis
